// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hovvxvdrzlpiwzwlkdye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvdnZ4dmRyemxwaXd6d2xrZHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0MjA5NDEsImV4cCI6MjEwMDk5Njk0MX0.czmpofxogdCQ2nj_A-bbfTJ0zLqrjUYaCoipYoj8Yj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});